services:
  frontend:
    # image: frontend
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - front-tier
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf # Nginx yapılandırma dosyasını mount et
      - ./frontend:/usr/share/nginx/html # Frontend dosyalarını mount et
    

  backend:
    # image: backend
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    networks:
      - front-tier
    env_file: 
      - .env # .env dosyasını yükler

  deid_db:
    image: mysql:5.7
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - front-tier

volumes:
  mysql-volume:

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  