- name: Create Kubeconfig for Jenkins
  hosts: master
  become: true
  tasks:
    - name: Get Kubernetes API server URL
      command: kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'
      register: api_server

    - name: Get ServiceAccount token
      command: |
        kubectl get secret $(kubectl get sa jenkins-sa -o jsonpath='{.secrets[0].name}') -o jsonpath='{.data.token}' | base64 --decode
      register: jenkins_token

    - name: Create kubeconfig file
      copy:
        content: |
          apiVersion: v1
          kind: Config
          clusters:
          - cluster:
              server: "{{ api_server.stdout }}"
              insecure-skip-tls-verify: true
            name: kubernetes
          contexts:
          - context:
              cluster: kubernetes
              user: jenkins-sa
            name: jenkins-context
          current-context: jenkins-context
          users:
          - name: jenkins-sa
            user:
              token: "{{ jenkins_token.stdout }}"
        dest: /tmp/kubeconfig

    - name: Set permissions on kubeconfig
      ansible.builtin.file:
        path: /tmp/kubeconfig
        owner: ec2-user
        group: ec2-user
        mode: '0600'
