mykey = "test"
ami = "ami-0592c673f0b1e7665"
region = "eu-central-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "test-app-secgr"
jenkins-server-tag = "Jenkins Server of test-app"
jenkins-profile = "test-app-jenkins-profile-tr"
jenkins-role = "test-jenkins-server-role"
