mykey = "test"
ami = "ami-08a0d1e16fc3f61ea"
region = "us-east-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "test-app-secgr"
jenkins-server-tag = "Jenkins Server of test-app"
jenkins-profile = "test-app-jenkins-profile-tr"
jenkins-role = "test-jenkins-server-role"
