apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 891377165332.dkr.ecr.eu-central-1.amazonaws.com/backend-repo:latest  # ECR repository ile uyumlu hale getirildi
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_USER
          value: "raife"
        - name: MYSQL_PASSWORD
          value: "123"
        - name: MYSQL_DATABASE
          value: "deid"
        - name: MYSQL_HOST
          value: "mysql-service"  # MySQL service ile bağlantı kuracak
        - name: MYSQL_PORT
          value: "3306"